export enum Resources {
    AshTree = 'ash_tree',
    BassFishingSpot = 'bass_fishing_spot',
    BirchTree = 'birch_tree',
    CoalRocks = 'coal_rocks',
    CopperRocks = 'copper_rocks',
    DeadTree = 'dead_tree',
    Glowstem = 'glowstem',
    GoldRocks = 'gold_rocks',
    GudgeonFishingSpot = 'gudgeon_fishing_spot',
    IronRocks = 'iron_rocks',
    MagicTree = 'magic_tree',
    MapleTree = 'maple_tree',
    MithrilRocks = 'mithril_rocks',
    Nettle = 'nettle',
    SalmonFishingSpot = 'salmon_fishing_spot',
    ShrimpFishingSpot = 'shrimp_fishing_spot',
    SpruceTree = 'spruce_tree',
    StrangeRocks = 'strange_rocks',
    SunflowerField = 'sunflower_field',
    TroutFishingSpot = 'trout_fishing_spot',
}
